version: "3.8"

services:
  redis:
    image: redis:7.4-alpine
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--save", "20", "1", "--loglevel", "warning"]
    restart: always

volumes:
  redis_data:
